### ISSUE TITLE
Installing the plugin fails for poetry latest release 1.7

### ISSUE THREAD

**Issue by zetahernandez** [arcesium/poetry-plugin-pypi-mirror#14]
```
failed to solve: process poetry self add poetry-plugin-pypi-mirror
11.28 Because no versions of poetry-plugin-pypi-mirror match >0.4.0,<0.5.0
11.28  and poetry-plugin-pypi-mirror (0.4.0) depends on poetry (>=1.3,<1.7), poetry-plugin-pypi-mirror (>=0.4.0,<0.5.0) requires poetry (>=1.3,<1.7).
11.28 So, because poetry-instance depends on both poetry (1.7.0) and poetry-plugin-pypi-mirror (^0.4.0), version solving failed.
```

**Comment by JacobHenner** [comment]
Thanks for the report - because this plugin depends on interacting with the internals of Poetry, we deliberately restrict the versioning compatibility of the plugin to ensure it remains operable when a new version of Poetry is released. This process is not yet automated. I'll review compatibility with 1.7 (which was released 1h ago), and publish a new release once confirmed as compatible. I expect this will occur within the next few days.

**Comment by zetahernandez** [comment]
Thanks Jacob! Wondering if makes sense to change the strategy to allow the forward compatibility even without checking if the  plugins works or not with the new versions of poetry? And just wait for the report of an issue only in case internals change and the plugins fails.

**Comment by JacobHenner** [comment]
> Thanks Jacob! Wondering if makes sense to change the strategy to allow the forward compatibility even without checking if the plugins works or not with the new versions of poetry? And just wait for the report of an issue only in case internals change and the plugins fails.

I've considered this, but for now I'd prefer to take action to verify compatibility with new releases of Poetry. My concern is that a new release can silently break the plugin, which might go unnoticed in environments where PyPI.org is available but not preferred (or prohibited by policy).

Perhaps certifying the plugin against new releases could be fully automated, including incrementing the compatibility metadata if tests pass.
